slatwallqs:
  build: .
  ports:
   - "80:8080"
   - "3306:3306"
  environment:
   MYSQL_HOST : localhost
   MYSQL_ROOT_PASSWORD : MakeThisSecret!
   MYSQL_DATABASE : Slatwall
   LUCEE_PASSWORD: AlsoChangeThis!