web:
  build: .
  ports:
   - "80:8080"
  volumes:
   - src:/var/www
  links:
   - mysql
mysql:
  image: mysql
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD : changeme
   MYSQL_DATABASE : slatwall