---
webqa:
  build: .
  ports:
   - "80:8080"
  environment:
   MYSQL_HOST : localhost
   MYSQL_ROOT_PASSWORD : QaPa33W0RD
   MYSQL_DATABASE : Slatwall
   LUCEE_PASSWORD: QaPa33W0RD
   SLATWALL_VERSION_OR_BRANCH: master
...
